### ISSUE TITLE
Zero-indexed lines and columns

### ISSUE THREAD

**Issue by joliss** [estree/estree#73] opened 2015-04-04 15:51 UTC
We're in the process of speccing out error objects for the Broccoli build tool (which powers Ember CLI, among other things), and we'd like to solicit your opinion on whether Broccoli should make lines and columns 0-indexed or 1-indexed:

```js
err.broccoliInfo.firstLine // 0-indexed? 1-indexed?
err.broccoliInfo.firstColumn // 0-indexed? 1-indexed?
```

The choice here mostly affects whether Broccoli's API is easy to use and understand - plugins will simply add or subtract 1 to convert between conventions as necessary.

My first intuition was to make `line` and `column` both 1-indexed, because that's what we want to display. But @sebmck pointed out to me that ESTree (and thus Esprima and Acorn) make `line` 1-indexed and `column` 0-indexed. This seems a bit surprising to me; and it's not universal - e.g. libsass uses 1-indexed `line` and `column`, and coffee-script uses 0-indexed `line` and `column`. But if ESTree's "1-indexed `line` and 0-indexed `column`" thing is common enough, it might be worth copying for us.

So I'd like to know:

1. How common is ESTree's "1-indexed `line` and 0-indexed `column`" convention in and outside of JavaScript land?

2. Do you have any opinion on which convention Broccoli should use?

3. Are there any conventions for whether ranges are inclusive or exclusive (e.g. represented by `firstLine`, `firstColumn`, `lastLine`, `lastColumn`)?

**Comment by sebmck** [comment] 2015-04-04 16:03
Duplicate of #65.

On Sunday, 5 April 2015, Jo Liss <notifications@github.com> wrote:

> We're in the process of speccing out error objects for the Broccoli build
> tool (which powers Ember CLI, among other things), and we'd like to solicit
> your opinion on whether we should lines and columns 0-indexed or 1-indexed:
>
> err.broccoliInfo.firstLine // 0-indexed? 1-indexed?
> err.broccoliInfo.firstColumn // 0-indexed? 1-indexed?
>
> The choice here mostly affects whether Broccoli's API is easy to use and
> understand - plugins will simply add or subtract 1 to convert between
> conventions as necessary.
>
> My first intuition was to make line and column both 1-indexed, because
> that's what we want to display. But @sebmck <https://github.com/sebmck>
> pointed out to me that ESTree (and thus Esprima and Acorn) make line
> 1-indexed and column 0-indexed. This seems a bit surprising to me; and
> it's not universal - e.g. libsass uses 1-indexed line and column, and
> coffee-script uses 0-indexed line and column. But if ESTree's "1-indexed
> line and 0-indexed column" thing is common enough, it might be worth
> copying for us.
>
> So I'd like to know:
>
>    1.
>
>    How common is ESTree's "1-indexed line and 0-indexed column"
>    convention in and outside of JavaScript?
>    2.
>
>    Do you have any opinion on how we should decide?
>    3.
>
>    Are there any conventions for whether ranges are inclusive or
>    exclusive (e.g. represented by firstLine, firstColumn, lastLine,
>    lastColumn)?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/73>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment] 2015-04-04 16:07
Also FWIW, source maps are also zero column indexed.

On Sunday, 5 April 2015, Sebastian McKenzie <sebmck@gmail.com> wrote:

> Duplicate of #65.
>
> On Sunday, 5 April 2015, Jo Liss <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> We're in the process of speccing out error objects for the Broccoli build
>> tool (which powers Ember CLI, among other things), and we'd like to solicit
>> your opinion on whether we should lines and columns 0-indexed or 1-indexed:
>>
>> err.broccoliInfo.firstLine // 0-indexed? 1-indexed?
>> err.broccoliInfo.firstColumn // 0-indexed? 1-indexed?
>>
>> The choice here mostly affects whether Broccoli's API is easy to use and
>> understand - plugins will simply add or subtract 1 to convert between
>> conventions as necessary.
>>
>> My first intuition was to make line and column both 1-indexed, because
>> that's what we want to display. But @sebmck <https://github.com/sebmck>
>> pointed out to me that ESTree (and thus Esprima and Acorn) make line
>> 1-indexed and column 0-indexed. This seems a bit surprising to me; and
>> it's not universal - e.g. libsass uses 1-indexed line and column, and
>> coffee-script uses 0-indexed line and column. But if ESTree's "1-indexed
>> line and 0-indexed column" thing is common enough, it might be worth
>> copying for us.
>>
>> So I'd like to know:
>>
>>    1.
>>
>>    How common is ESTree's "1-indexed line and 0-indexed column"
>>    convention in and outside of JavaScript?
>>    2.
>>
>>    Do you have any opinion on how we should decide?
>>    3.
>>
>>    Are there any conventions for whether ranges are inclusive or
>>    exclusive (e.g. represented by firstLine, firstColumn, lastLine,
>>    lastColumn)?
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/estree/estree/issues/73>.
>>
>
>
> --
> Sebastian McKenzie
>


-- 
Sebastian McKenzie

**Comment by joliss** [comment] 2015-04-04 16:14
> Duplicate of #65.

Wait wait, I'm not saying ESTree should change something. I'm asking for help/opinions re the Broccoli spec.

> Also FWIW, source maps are also zero column indexed.

Interesting... And zero line indexed as well.

**Comment by nzakas** [comment] 2015-04-04 16:33
AFAIK, each parser is using 1-based lines and 0-based columns. I've yet to come across 1-based columns anywhere.

**Comment by sebmck** [comment] 2015-04-04 16:36
@joliss 

> Wait wait, I'm not saying ESTree should change something. I'm asking for help/opinions re the Broccoli spec.

Oh right. Misread, sorry!

**Comment by sebmck** [comment] 2015-04-04 16:56
@joliss 

> And zero line indexed as well.

[Apparently not](https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-consumer.js#L482-485).

**Comment by btmills** [comment] 2015-04-04 17:46
> Are there any conventions for whether ranges are inclusive or exclusive

`SourceLocation`s have an inclusive start and exclusive end. Quoting [the spec](https://github.com/estree/estree/blob/master/spec.md):

> a start position (the position of the first character of the parsed source region) and an end position (the position of the first character after the parsed source region)

Though `range` is not standardized, it has the same behavior in tools I've seen.

**Comment by mikesherov** [comment] 2015-06-24 00:03
Seems like this issue is resolved then? I'll reopen should anyone reply once I close.

**Closed by mikesherov** 2015-06-24 00:03 UTC
