### ISSUE TITLE
In ImportSpecifier, the two Identifiers can have overlapping location information

### ISSUE THREAD

**Issue by ikarienator** [estree/estree#42] opened 2015-03-04 21:29 UTC
For example:

```es6
import {a} from "a";
```

Will parse into a ImportSpecifier with duplicate `imported` and `local` Identifiers. They would hold overlapping location information.

**Comment by RReverser** [comment] 2015-03-04 22:46
Such a duplication was brought to simplify handling of such shortenings and allow them to be processed just in the same way as `a as a` in AST tools. Why do you think that is an issue?

**Comment by sebmck** [comment] 2015-03-05 00:01
Same goes for object property shorthand `var obj = { x, y };`. What do you propose is the solution?

**Comment by nzakas** [comment] 2015-03-05 01:33
I think it's okay as it is. The object property shorthand that @sebmck references really helps with AST consumers.

**Comment by sebmck** [comment] 2015-03-05 01:43
Yeah, agreed. Not even sure how you'd get around this without adding an
additional node type which I'd be strongly against.

On Thursday, 5 March 2015, Nicholas C. Zakas <notifications@github.com>
wrote:

> I think it's okay as it is. The object property shorthand that @sebmck
> <https://github.com/sebmck> references really helps with AST consumers.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/estree/estree/issues/42#issuecomment-77288777>.
>


-- 
Sebastian McKenzie

**Comment by michaelficarra** [comment] 2015-03-05 01:47
@sebmck: In the Shift AST, we made the `name` field optional: https://github.com/shapesecurity/shift-spec/blob/ce703795a855f66081242c7356547742b7e78fa4/spec.idl#L177-L180

**Comment by RReverser** [comment] 2015-03-12 16:50
I'm closing this as "by design".

**Closed by RReverser** 2015-03-12 16:50 UTC
