### ISSUE TITLE
"NewExpression" is not assignable to "CallExpression"

### ISSUE THREAD

**Issue by krisselden** [estree/estree#141] opened 2016-11-30 05:46 UTC
Interfaces with specific string values for type should be leaves.

Interface NewExpression should not extend CallExpression otherwise CallExpression's type would be `type: "CallExpression" | "NewExpression"`

**Comment by RReverser** [comment] 2016-11-30 16:04
I guess see #140 as relevant.

> otherwise CallExpression's type would be type: "CallExpression" | "NewExpression"

It wouldn't be, `<:` to a new interface does not modify the base object.

**Comment by krisselden** [comment] 2016-12-01 04:46
@RReverser I realize it doesn't modify the base but I was trying to illustrate that in order for NewExpression to extend CallExpression, that would need to be the type, you can only narrow a property's type you can't change it to something not assignable to the base, and "NewExpression" is not assignable to "CallExpression".

This became apparent when I tried these interfaces in TypeScript and this was the error I got when I tried to compile. 

Once an interface has a string literal as its type it should be a leaf and nothing should extend it.  This is also whats expected when doing a switch case on type.

On a similar note, it would be clearer if `regex` was an optional field of `Literal` since there is no `type: "RegExpLiteral"`, since you'd need to check the presence of regex anyway after checking that the type was `"Literal"`

**Comment by RReverser** [comment] 2016-12-01 18:38
> This became apparent when I tried these interfaces in TypeScript and this was the error I got when I tried to compile. Once an interface has a string literal as its type it should be a leaf and nothing should extend it.

As I said, see the issue referenced above, this and other questions were discussed. For TypeScript, there are DefinitelyTyped definition you can install with `npm i @types/estree`.

They're surely very different because this DSL the spec uses is not and is not intended to be compatible with specifically TypeScript's type system.

It's here purely for node description purposes, and is inherited from / compatible with Mozilla's [Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) docs.

**Comment by krisselden** [comment] 2016-12-02 05:23
The Parser API you linked doesn't have this issue,  NewExpression inherits from Expression, I would be happy with this.

Changing it to match the Parser API would fix this and this wouldn't break anything.  It has nothing to do specifically with TypeScript it just doesn't make any sense for the specific type strings not to match terminal interfaces.  NewExpression is not a CallExpression, look at the API docs you linked.

**Comment by RReverser** [comment] 2016-12-02 13:22
> it just doesn't make any sense for the specific type strings not to match terminal interfaces

Why? Interface names are purely for distinguishing interfaces. For example, in ES6 `AssignmentProperty` also inherits from `Property`, and has new interface name but surely same `type: "Property"` as its parent. This is normal practice in these spec docs, but if it doesn't work in some type system (like TypeScript), then better to provide tooling-specific fix on its side, like ESTree TypeScript definitions do for many things including overriding `type`, overriding `ArrowFunction` body type, changed tag interfaces to union types etc. etc..

**Comment by mikesherov** [comment] 2017-02-10 16:45
Closing as this seems like works as intended. Please comment if that's incorrect.

**Closed by mikesherov** 2017-02-10 16:45 UTC

**Comment by RReverser** [comment] 2017-02-10 18:01
@mikesherov Additionally, the original suggestion was implemented as part of another issue anyway.
