### ISSUE TITLE
AST definition for Stage 4 Hashbang Grammer?

### ISSUE THREAD

**Issue by sosukesuzuki** [estree/estree#286] opened 2022-08-08 15:10 UTC
Now [Hashbang Grammer](https://github.com/tc39/proposal-hashbang) has been Stage 4.

ESTree should include AST definition for Hashbang Grammer comment?

Currently, ASTs seem to widely by implementation:

**Source:**

```js
#!hello
```

**Babel:**

```json
{
  "type": "File",
  "program": {
    "type": "Program",
    "sourceType": "module",
    "interpreter": {
      "type": "InterpreterDirective",
      "value": "hello"
    },
    "body": [],
    "directives": []
  },
  "comments": []
}

```

**Acorn:**

```json
{
  "type": "Program",
  "body": [],
  "comments": [
    {
      "type": "Line",
      "value": "hello"
    }
  ]
}

```

**Comment by JLHwung** [comment] 2022-08-08 17:48
Duplicate of #224.

**Closed by JLHwung** 2022-08-08 17:48 UTC

**Comment by michaelficarra** [comment] 2022-08-08 18:04
An additional optional property on the Program node, somewhat like Babel, seems like the right call. There's either 1 or 0 shebang per Program, and they're not allowed anywhere else. Acorn's implementation is problematic as it conflates shebangs with leading comments, losing that information.
