### ISSUE TITLE
UnaryExpression "prefix" is always true

### ISSUE THREAD

**Issue by mroch** [estree/estree#147] opened 2017-01-30 07:56 UTC
The `prefix` property of `UnaryExpression` seems like it will always be `true`. I'm guessing it's there based on [§12.5 UnaryExpression](http://www.ecma-international.org/ecma-262/6.0/#sec-unary-operators) which includes `PostfixExpression`, but estree puts those into `UpdateExpression` instead.

Proposal: delete the `prefix` property from `UnaryExpression`.

**Comment by RReverser** [comment] 2017-01-30 09:27
Looks like duplicate of https://github.com/estree/estree/pull/118.

**Closed by RReverser** 2017-01-30 09:27 UTC

**Comment by mroch** [comment] 2017-01-30 09:48
My bad, searched for issues but not PRs. Thanks!
