### ISSUE TITLE
descriptions?

### ISSUE THREAD

**Issue by acthp** [estree/estree#175] opened 2017-11-30 17:43 UTC
Are there descriptions of these types anywhere? This project appears to specify types and properties of AST nodes, but not what they represent. Where can I find, for example, what an ArrayPattern is? Or a Directive?

**Comment by michaelficarra** [comment] 2017-11-30 18:49
Yes, I think this is so important! We had the same issue in the Shift spec (https://github.com/shapesecurity/shift-spec/issues/69) and solved it via inline prose (https://github.com/shapesecurity/shift-spec/pull/117).

**Comment by RReverser** [comment] 2017-11-30 19:34
Looks like duplicate of https://github.com/estree/estree/issues/66.

**Closed by RReverser** 2017-11-30 19:34 UTC
