### ISSUE TITLE
Add documentation to ES6 features

### ISSUE THREAD

**Issue by GabrielRatener** [estree/estree#108] opened 2015-11-19 02:16 UTC
Certain ES6 tree specifications are not thoroughly documented which is problematic for non-obvious parts of the spec such as template literals.

**Comment by RReverser** [comment] 2015-11-19 12:57
Duplicate of #66 or do you want anything else?

**Comment by GabrielRatener** [comment] 2015-11-19 19:11
I wasn't looking for examples as #66 , rather I am calling for some undocumented parts of the spec, especially those of ES6, to be explained. Parts of the spec, such as template literals, are specified but there is no documentation describing what for example a quasi is, or what an expression represents or the rules for where they must each go (must there be  a leading string?, etc...).

**Comment by RReverser** [comment] 2015-11-19 20:00
> describing what for example a quasi is, or what an expression represents or the rules for where they must each go (must there be a leading string?, etc...)

That sounds exactly like examples to me. Other than showing what goes where from the source into AST, I don't see what can be documented here.

**Comment by mikesherov** [comment] 2017-02-10 16:48
Closing as stale.

**Closed by mikesherov** 2017-02-10 16:48 UTC
